export const seedTeams = [
  { name: "Mexico", group_name: "A" },
  { name: "Africa do Sul", group_name: "A" },
  { name: "Coreia do Sul", group_name: "A" },
  { name: "Republica Tcheca", group_name: "A" },
  { name: "Canada", group_name: "B" },
  { name: "Bosnia e Herzegovina", group_name: "B" },
  { name: "Catar", group_name: "B" },
  { name: "Suica", group_name: "B" },
  { name: "Brasil", group_name: "C" },
  { name: "Marrocos", group_name: "C" },
  { name: "Haiti", group_name: "C" },
  { name: "Escocia", group_name: "C" },
  { name: "Estados Unidos", group_name: "D" },
  { name: "Paraguai", group_name: "D" },
  { name: "Australia", group_name: "D" },
  { name: "Turquia", group_name: "D" },
  { name: "Alemanha", group_name: "E" },
  { name: "Curacao", group_name: "E" },
  { name: "Costa do Marfim", group_name: "E" },
  { name: "Equador", group_name: "E" },
  { name: "Paises Baixos", group_name: "F" },
  { name: "Japao", group_name: "F" },
  { name: "Suecia", group_name: "F" },
  { name: "Tunisia", group_name: "F" },
  { name: "Belgica", group_name: "G" },
  { name: "Egito", group_name: "G" },
  { name: "Ira", group_name: "G" },
  { name: "Nova Zelandia", group_name: "G" },
  { name: "Espanha", group_name: "H" },
  { name: "Cabo Verde", group_name: "H" },
  { name: "Arabia Saudita", group_name: "H" },
  { name: "Uruguai", group_name: "H" },
  { name: "Franca", group_name: "I" },
  { name: "Senegal", group_name: "I" },
  { name: "Noruega", group_name: "I" },
  { name: "Iraque", group_name: "I" },
  { name: "Argentina", group_name: "J" },
  { name: "Argelia", group_name: "J" },
  { name: "Austria", group_name: "J" },
  { name: "Jordania", group_name: "J" },
  { name: "Portugal", group_name: "K" },
  { name: "RD Congo", group_name: "K" },
  { name: "Uzbequistao", group_name: "K" },
  { name: "Colombia", group_name: "K" },
  { name: "Inglaterra", group_name: "L" },
  { name: "Croacia", group_name: "L" },
  { name: "Gana", group_name: "L" },
  { name: "Panama", group_name: "L" }
];

export const teamNameTranslations = {
  Belgium: "Bélgica",
  Belgica: "Bélgica",
  Brazil: "Brasil",
  Canada: "Canadá",
  Croatia: "Croácia",
  Croacia: "Croácia",
  Denmark: "Dinamarca",
  England: "Inglaterra",
  France: "França",
  Franca: "França",
  Germany: "Alemanha",
  Ghana: "Gana",
  Italy: "Itália",
  Japan: "Japão",
  Japao: "Japão",
  "Korea Republic": "Coreia do Sul",
  "South Korea": "Coreia do Sul",
  Mexico: "México",
  Morocco: "Marrocos",
  Netherlands: "Países Baixos",
  "Paises Baixos": "Países Baixos",
  Poland: "Polônia",
  Qatar: "Catar",
  "Saudi Arabia": "Arábia Saudita",
  "Arabia Saudita": "Arábia Saudita",
  Serbia: "Sérvia",
  Spain: "Espanha",
  Switzerland: "Suíça",
  Suica: "Suíça",
  "United States": "Estados Unidos",
  USA: "Estados Unidos",
  Uruguay: "Uruguai",
  "South Africa": "África do Sul",
  "Africa do Sul": "África do Sul",
  Czechia: "República Tcheca",
  "Czech Republic": "República Tcheca",
  "Republica Tcheca": "República Tcheca",
  "Bosnia & Herzegovina": "Bósnia e Herzegovina",
  "Bosnia e Herzegovina": "Bósnia e Herzegovina",
  Turkey: "Turquia",
  Turkiye: "Turquia",
  "Ivory Coast": "Costa do Marfim",
  Ecuador: "Equador",
  Curacao: "Curaçao",
  Sweden: "Suécia",
  Suecia: "Suécia",
  Iran: "Irã",
  Ira: "Irã",
  "New Zealand": "Nova Zelândia",
  "Nova Zelandia": "Nova Zelândia",
  "Cape Verde": "Cabo Verde",
  Norway: "Noruega",
  Iraq: "Iraque",
  Algeria: "Argélia",
  Argelia: "Argélia",
  Austria: "Áustria",
  Jordan: "Jordânia",
  Jordania: "Jordânia",
  "DR Congo": "RD Congo",
  Uzbekistan: "Uzbequistão",
  Uzbequistao: "Uzbequistão",
  Australia: "Austrália",
  Escocia: "Escócia",
  Tunisia: "Tunísia",
  Colombia: "Colômbia",
  Panama: "Panamá"
};

const match = (date, timeEt, group, home, away, venue) => ({
  stage: "GROUP",
  round_name: `Grupo ${group}`,
  home_team: home,
  away_team: away,
  kickoff_at: toUtcIso(date, timeEt),
  status: "SCHEDULED",
  venue
});

function toUtcIso(date, timeEt) {
  const [hour, minute] = timeEt.split(":").map(Number);
  const utcHour = hour + 4;
  const kickoff = new Date(`${date}T00:00:00.000Z`);
  kickoff.setUTCDate(kickoff.getUTCDate() + Math.floor(utcHour / 24));
  kickoff.setUTCHours(utcHour % 24, minute, 0, 0);
  return kickoff.toISOString();
}

export const seedMatches = [
  match("2026-06-11", "15:00", "A", "Mexico", "Africa do Sul", "Estadio Banorte, Cidade do Mexico"),
  match("2026-06-11", "22:00", "A", "Coreia do Sul", "Republica Tcheca", "Estadio Akron, Guadalajara"),
  match("2026-06-12", "15:00", "B", "Canada", "Bosnia e Herzegovina", "BMO Field, Toronto"),
  match("2026-06-12", "21:00", "D", "Estados Unidos", "Paraguai", "SoFi Stadium, Inglewood"),
  match("2026-06-14", "00:00", "D", "Australia", "Turquia", "BC Place, Vancouver"),
  match("2026-06-13", "15:00", "B", "Catar", "Suica", "Levi's Stadium, Santa Clara"),
  match("2026-06-13", "18:00", "C", "Brasil", "Marrocos", "MetLife Stadium, East Rutherford"),
  match("2026-06-13", "21:00", "C", "Haiti", "Escocia", "Gillette Stadium, Foxborough"),
  match("2026-06-14", "13:00", "E", "Alemanha", "Curacao", "NRG Stadium, Houston"),
  match("2026-06-14", "16:00", "F", "Paises Baixos", "Japao", "AT&T Stadium, Arlington"),
  match("2026-06-14", "19:00", "E", "Costa do Marfim", "Equador", "Lincoln Financial Field, Philadelphia"),
  match("2026-06-14", "22:00", "F", "Tunisia", "Suecia", "Estadio BBVA, Monterrey"),
  match("2026-06-15", "12:00", "H", "Espanha", "Cabo Verde", "Mercedes-Benz Stadium, Atlanta"),
  match("2026-06-15", "15:00", "G", "Belgica", "Egito", "Lumen Field, Seattle"),
  match("2026-06-15", "18:00", "H", "Arabia Saudita", "Uruguai", "Hard Rock Stadium, Miami Gardens"),
  match("2026-06-15", "21:00", "G", "Ira", "Nova Zelandia", "SoFi Stadium, Inglewood"),
  match("2026-06-17", "00:00", "J", "Austria", "Jordania", "Levi's Stadium, Santa Clara"),
  match("2026-06-16", "15:00", "I", "Franca", "Senegal", "MetLife Stadium, East Rutherford"),
  match("2026-06-16", "18:00", "I", "Noruega", "Iraque", "Gillette Stadium, Foxborough"),
  match("2026-06-16", "21:00", "J", "Argentina", "Argelia", "GEHA Field at Arrowhead, Kansas City"),
  match("2026-06-17", "13:00", "K", "Portugal", "RD Congo", "NRG Stadium, Houston"),
  match("2026-06-17", "16:00", "L", "Inglaterra", "Croacia", "AT&T Stadium, Arlington"),
  match("2026-06-17", "19:00", "L", "Gana", "Panama", "BMO Field, Toronto"),
  match("2026-06-17", "22:00", "K", "Uzbequistao", "Colombia", "Estadio Banorte, Cidade do Mexico"),
  match("2026-06-18", "12:00", "A", "Africa do Sul", "Republica Tcheca", "Mercedes-Benz Stadium, Atlanta"),
  match("2026-06-18", "15:00", "B", "Suica", "Bosnia e Herzegovina", "SoFi Stadium, Inglewood"),
  match("2026-06-18", "18:00", "B", "Canada", "Catar", "BC Place, Vancouver"),
  match("2026-06-18", "21:00", "A", "Mexico", "Coreia do Sul", "Estadio Akron, Guadalajara"),
  match("2026-06-19", "23:00", "D", "Paraguai", "Turquia", "Levi's Stadium, Santa Clara"),
  match("2026-06-19", "18:00", "C", "Escocia", "Marrocos", "Gillette Stadium, Foxborough"),
  match("2026-06-19", "15:00", "D", "Estados Unidos", "Australia", "Lumen Field, Seattle"),
  match("2026-06-19", "20:30", "C", "Brasil", "Haiti", "Lincoln Financial Field, Philadelphia"),
  match("2026-06-21", "00:00", "F", "Tunisia", "Japao", "Estadio BBVA, Monterrey"),
  match("2026-06-20", "13:00", "F", "Paises Baixos", "Suecia", "NRG Stadium, Houston"),
  match("2026-06-20", "16:00", "E", "Alemanha", "Costa do Marfim", "BMO Field, Toronto"),
  match("2026-06-20", "20:00", "E", "Equador", "Curacao", "GEHA Field at Arrowhead, Kansas City"),
  match("2026-06-21", "12:00", "H", "Espanha", "Arabia Saudita", "Mercedes-Benz Stadium, Atlanta"),
  match("2026-06-21", "15:00", "G", "Belgica", "Ira", "SoFi Stadium, Inglewood"),
  match("2026-06-21", "18:00", "H", "Uruguai", "Cabo Verde", "Hard Rock Stadium, Miami Gardens"),
  match("2026-06-21", "21:00", "G", "Nova Zelandia", "Egito", "BC Place, Vancouver"),
  match("2026-06-22", "13:00", "J", "Argentina", "Austria", "AT&T Stadium, Arlington"),
  match("2026-06-22", "17:00", "I", "Franca", "Iraque", "Lincoln Financial Field, Philadelphia"),
  match("2026-06-22", "20:00", "I", "Noruega", "Senegal", "MetLife Stadium, East Rutherford"),
  match("2026-06-22", "23:00", "J", "Jordania", "Argelia", "Levi's Stadium, Santa Clara"),
  match("2026-06-23", "13:00", "K", "Portugal", "Uzbequistao", "NRG Stadium, Houston"),
  match("2026-06-23", "16:00", "L", "Inglaterra", "Gana", "Gillette Stadium, Foxborough"),
  match("2026-06-23", "19:00", "L", "Panama", "Croacia", "BMO Field, Toronto"),
  match("2026-06-23", "22:00", "K", "Colombia", "RD Congo", "Estadio Akron, Guadalajara"),
  match("2026-06-24", "15:00", "B", "Canada", "Suica", "BC Place, Vancouver"),
  match("2026-06-24", "15:00", "B", "Catar", "Bosnia e Herzegovina", "Lumen Field, Seattle"),
  match("2026-06-24", "18:00", "C", "Escocia", "Brasil", "Hard Rock Stadium, Miami Gardens"),
  match("2026-06-24", "18:00", "C", "Marrocos", "Haiti", "Mercedes-Benz Stadium, Atlanta"),
  match("2026-06-24", "21:00", "A", "Mexico", "Republica Tcheca", "Estadio Banorte, Cidade do Mexico"),
  match("2026-06-24", "21:00", "A", "Coreia do Sul", "Africa do Sul", "Estadio BBVA, Monterrey"),
  match("2026-06-25", "16:00", "E", "Equador", "Alemanha", "MetLife Stadium, East Rutherford"),
  match("2026-06-25", "16:00", "E", "Curacao", "Costa do Marfim", "Lincoln Financial Field, Philadelphia"),
  match("2026-06-25", "19:00", "F", "Tunisia", "Paises Baixos", "GEHA Field at Arrowhead, Kansas City"),
  match("2026-06-25", "19:00", "F", "Japao", "Suecia", "AT&T Stadium, Arlington"),
  match("2026-06-25", "22:00", "D", "Estados Unidos", "Turquia", "SoFi Stadium, Inglewood"),
  match("2026-06-25", "22:00", "D", "Paraguai", "Australia", "Levi's Stadium, Santa Clara"),
  match("2026-06-26", "15:00", "I", "Noruega", "Franca", "Gillette Stadium, Foxborough"),
  match("2026-06-26", "15:00", "I", "Senegal", "Iraque", "BMO Field, Toronto"),
  match("2026-06-26", "20:00", "H", "Uruguai", "Espanha", "Estadio Akron, Guadalajara"),
  match("2026-06-26", "20:00", "H", "Cabo Verde", "Arabia Saudita", "NRG Stadium, Houston"),
  match("2026-06-26", "23:00", "G", "Nova Zelandia", "Belgica", "BC Place, Vancouver"),
  match("2026-06-26", "23:00", "G", "Egito", "Ira", "Lumen Field, Seattle"),
  match("2026-06-27", "17:00", "L", "Panama", "Inglaterra", "MetLife Stadium, East Rutherford"),
  match("2026-06-27", "17:00", "L", "Croacia", "Gana", "Lincoln Financial Field, Philadelphia"),
  match("2026-06-27", "19:30", "K", "Colombia", "Portugal", "Hard Rock Stadium, Miami Gardens"),
  match("2026-06-27", "19:30", "K", "Uzbequistao", "RD Congo", "Mercedes-Benz Stadium, Atlanta"),
  match("2026-06-27", "22:00", "J", "Jordania", "Argentina", "AT&T Stadium, Arlington"),
  match("2026-06-27", "22:00", "J", "Argelia", "Austria", "GEHA Field at Arrowhead, Kansas City")
];

export const knockoutSlots = [
  "1A",
  "2A",
  "3A",
  "1B",
  "2B",
  "3B",
  "1C",
  "2C",
  "3C",
  "1D",
  "2D",
  "3D",
  "1E",
  "2E",
  "3E",
  "1F",
  "2F",
  "3F",
  "1G",
  "2G",
  "3G",
  "1H",
  "2H",
  "3H",
  "1I",
  "2I",
  "3I",
  "1J",
  "2J",
  "3J",
  "1K",
  "2K",
  "3K",
  "1L",
  "2L",
  "3L"
];
